### PR TITLE
adding `prevStep` method on HIT

### PR DESCRIPTION
**Pull request by eldrin**
Hi, I simply added `.prevStep` method by pretty much re-using the `.nextStep` method. Please review and merge to the master if it is okay :)

### CODE REVIEW

**Comment by ShinNoNoir** [comment]
Could you also add an example or [extend an existing one](http://shinnonoir.github.io/commonhit/)? Currently, the files in the examples directory serve as a form of documentation for this library.

**Comment by eldrin** [comment]
sure. then will send another pull request including that update.

**Comment by ShinNoNoir** [comment]
@eldrin You don't have to create a new PR. Just add more commits to your fork and they should automatically show up.

**Comment by eldrin** [comment]
even easier :) will do

**Comment by eldrin** [comment]
Hi again. updating the examples, found the example youtube clip seems gone. Can I also change the video? If you want me to do, any thoughts on license type or content you concern? I also have a [suggestion](https://www.youtube.com/watch?v=ByUCJATtC8s) :)

**Comment by ShinNoNoir** [comment]
@eldrin Hmm, wait... which YT video is gone? If I remember correctly, I only used a cat video from my channel: https://youtu.be/ogtG0ZKQOq4

**Comment by eldrin** [comment]
@ShinNoNoir when running the example, console says `lllplayer is not defined`

screen shot 2019-01-16 at 22 32 08

**Comment by ShinNoNoir** [comment]
@eldrin Hmm... I notice an encoding issue listed in the console. While it's true no encoding is specified in the HTML source of the examples, the current examples should only contain 7-bit ASCII characters. Could you check with your editor what encoding the file has? For example, in VS Code, the encoding is shown in the lower right (status bar).

**Comment by eldrin** [comment]
@ShinNoNoir In my `vscode`, it's indicated as `UTF-8`.

**Comment by ShinNoNoir** [comment]
That's odd... Could you perhaps try zipping the modified file and email it to me?

Also, try setting up a local server and view the page via http: instead of file:. For example, cd to where the file is and [start a server using Python](https://stackoverflow.com/questions/7943751/what-is-the-python-3-equivalent-of-python-m-simplehttpserver).

**Comment by eldrin** [comment]
Okay. running local server solves my problem. (on `example.html`, the video shows up normally, and everything is fine. But on `example-hit-annotation.html`, there are other errors seemingly related to the `lllplayer`. Do you want to put this as a separate issue?

screen shot 2019-01-16 at 23 50 42

**Comment by ShinNoNoir** [comment]
Hmm, can't reproduce that right now in Edge (W10M) and earlier today it worked fine in Chrome (W10), even though Chrome was complaining in the dev console about postMessage.

**Comment by eldrin** [comment]
okay, then I'll take a look for the above problem further if it is happened by my modification.

**Pull request merged**
